### ISSUE TITLE
i just want to say...

### ISSUE THREAD

**Issue by idontveapc** [machineonamission/twemoji-colr0#2]
it's hard to make the font on android.

there are python 3 interpreters/compilers that work limited, and fonttool’s requirement for its virtual environment couldn't be install on any (android atmost).

**Comment by HexCodeFFF** [comment]
Dude for the love of god I’m busy I have college and a job I don’t have the free time to do this nor do I even want to do it anyways

**Comment by HexCodeFFF** [comment]
I don’t know, please stop bothering me about this
If you want it so bad just emulate Linux and run it there
